# This is a basic workflow to help you get started with Actions

name: Ubuntu

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
    
      # Setup Miniconda for python env setup
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2.1.1

      # Show the directory layout
      - name: Show repository content
        run: ls
